version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: monitoring_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: metrics_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - grafanaprometheus_monitoring

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - grafanaprometheus_monitoring

volumes:
  mysql_data:

networks:
  grafanaprometheus_monitoring:
    external: true
    